### ISSUE TITLE
Feature nou: sistem de prieteni?

### ISSUE THREAD

**Issue by Oana-Ivan** [Bia103/Proiect-MDS#4]
Am putea să încercăm să realizăm un sistem de prieteni

**Comment by DLarisa** [comment]
Da. Și am putea să avem un sistem de follow. E ok?

**Comment by Bia103** [comment]
Vreau sa ma imprietenesc cu toate <3

**Comment by StegarescuAnaMaria** [comment]
Putem adauga in baza de date userii-prieteni.

**Comment by Oana-Ivan** [comment]
De acord

**Comment by DLarisa** [comment]
Și așa se va reține cine cu cine este prieten și mai putem adăuga un tabel nou cu prieteni.

**Comment by DLarisa** [comment]
@Bia103 și tu ești de acord?

**Comment by Bia103** [comment]
Desigur :))

**Comment by Bia103** [comment]
<3
